using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace WebStore.Models.DataBase
{
    public class SampleData : DropCreateDatabaseIfModelChanges<StoreItemsEntities>
    {
        protected override void Seed(StoreItemsEntities context)
        {
            var categories = new List<Category>
            {
                new Category { Name = "Music" },
                new Category { Name = "Books" },
                new Category { Name = "Board Games" },
                new Category { Name = "Computer Games" },
                new Category { Name = "Movies" },
            };

            var authors = new List<Author>
            {
                new Author { Name = "AC/DC" },
                new Author { Name = "Accept" },
                new Author { Name = "Aisha Duo" },
                new Author { Name = "Alice In Chains" },
                new Author { Name = "Amy Winehouse" },
                new Author { Name = "Anita Ward" },
                new Author { Name = "Antônio Carlos Jobim" },
                new Author { Name = "Apocalyptica" },
                new Author { Name = "Sid Meier" },
                new Author { Name = "Uwe Rosenberg" },
                new Author { Name = "Black Sabbath" },
                new Author { Name = "Francis Coppola" },
                new Author { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Author { Name = "Bruce Dickinson" },
                new Author { Name = "Buddy Guy" },
                new Author { Name = "Caetano Veloso" },
                new Author { Name = "Calexico" },
                new Author { Name = "Cássia Eller" },
                new Author { Name = "Chic" },
                new Author { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Author { Name = "Chico Buarque" },
                new Author { Name = "Guy Gavriel Kay" },
                new Author { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Author { Name = "Chris Cornell" },
                new Author { Name = "Christopher O'Riley" },
                new Author { Name = "Cidade Negra" },
                new Author { Name = "David Coverdale" },
                new Author { Name = "Deep Purple" },
                new Author { Name = "Dennis Chambers" },
                new Author { Name = "Dan Simmons" },
                new Author { Name = "Donna Summer" },
                new Author { Name = "Ed Motta" },
                new Author { Name = "Elis Regina" },
                new Author { Name = "Frank Herbert" },
                new Author { Name = "Eugene Ormandy" },
                new Author { Name = "Faith No More" },
                new Author { Name = "Falamansa" },
                new Author { Name = "George R.R. Martin" },
                new Author { Name = "Godsmack" },
                new Author { Name = "Reiner Knizia" },
                new Author { Name = "Gustav Mahler" },
                new Author { Name = "Incognito" },
                new Author { Name = "Iron Maiden" },
                new Author { Name = "James Levine" },
                new Author { Name = "Jamiroquai" },
                new Author { Name = "Jimi Hendrix" },
                new Author { Name = "Jorge Ben" },
                new Author { Name = "Jota Quest" },
                new Author { Name = "Judas Priest" },
                new Author { Name = "Julian Bream" },
                new Author { Name = "Led Zeppelin" },
                new Author { Name = "Lenny Kravitz" },
                new Author { Name = "Marillion" },
                new Author { Name = "Marisa Monte" },
                new Author { Name = "Maurizio Pollini" },
                new Author { Name = "Men At Work" },
                new Author { Name = "Miles Davis" },
                new Author { Name = "William Attia" },
                new Author { Name = "Nash Ensemble" },
                new Author { Name = "James Cameron" },
                new Author { Name = "Nirvana" },
                new Author { Name = "Olodum" },
                new Author { Name = "Orchestra of The Age of Enlightenment" },
                new Author { Name = "Os Paralamas Do Sucesso" },
                new Author { Name = "Ozzy Osbourne" },
                new Author { Name = "Page & Plant" },
                new Author { Name = "Pearl Jam" },
                new Author { Name = "Pink Floyd" },
                new Author { Name = "Queen" },
                new Author { Name = "Red Hot Chili Peppers" },
                new Author { Name = "Santana" },
                new Author { Name = "Scholars Baroque Ensemble" },
                new Author { Name = "Scorpions" },
                new Author { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Author { Name = "Soundgarden" },
                new Author { Name = "Temple of the Dog" },
                new Author { Name = "Peter Jackson" },
                new Author { Name = "The Black Crowes" },
                new Author { Name = "The Cult" },
                new Author { Name = "The King's Singers" },
                new Author { Name = "The Police" },
                new Author { Name = "The Rolling Stones" },
                new Author { Name = "The Who" },
                new Author { Name = "Tim Maia" },
                new Author { Name = "U2" },
                new Author { Name = "UB40" },
                new Author { Name = "Terry Pratchett" },
                new Author { Name = "Velvet Revolver" },
            };

            new List<Item>
            {
                new Item { Title = "For Those About To Music We Salute You", Category = categories.Single(g => g.Name == "Music"), Price = 8M, Author = authors.Single(a => a.Name == "AC/DC"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Let There Be Music", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "AC/DC"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Balls to the Wall", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Accept"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Restless and Wild", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Accept"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Quiet Songs", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aisha Duo"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Facelift", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Alice In Chains"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Frank", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Amy Winehouse"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ring My Bell", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Anita Ward"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chill: Brazil (Disc 2)", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Antônio Carlos Jobim"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Warner 25 Anos", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Antônio Carlos Jobim"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Plays Board Gameslica By Four Cellos", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Apocalyptica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Revelations", Category = categories.Single(g => g.Name == "Computer Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sid Meier"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Sid Meier's Pirates!", Category = categories.Single(g => g.Name == "Computer Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sid Meier"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Civilization V", Category = categories.Single(g => g.Name == "Computer Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sid Meier"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Agricola", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Uwe Rosenberg"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Le Havre", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Uwe Rosenberg"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Black Sabbath Vol. 4 (Remaster)", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Sabbath"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Black Sabbath", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Sabbath"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Godfather", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Francis Coppola"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Soprano Inspired", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chemical Wedding", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Bruce Dickinson"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Prenda Minha", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Caetano Veloso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Sozinho Remix Ao Vivo", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Caetano Veloso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Carried to Dust (Bonus Track Version)", Category = categories.Single(g => g.Name == "Computer Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Calexico"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Cássia Eller - Sem Limite [Disc 1]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cássia Eller"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Le Freak", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chic"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Scheherazade", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Minha Historia", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Buarque"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Last Lights of Sun", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guy Gavriel Kay"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Tigana", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guy Gavriel Kay"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Carry On", Category = categories.Single(g => g.Name == "Computer Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chris Cornell"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "SCRIABIN: Vers la flamme", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Christopher O'Riley"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Acústico MTV [Live]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cidade Negra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Cidade Negra - Hits", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cidade Negra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Into The Light", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "David Coverdale"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Come Taste The Band", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Deep Purple In Music", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Fireball", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Machine Head", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "MK III The Final Concerts [Disc 1]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Purpendicular", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Slaves And Masters", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Stormbringer", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Battle Rages On", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Final Concerts (Disc 2)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Outbreak", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dennis Chambers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Hyperion", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dan Simmons"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Illion", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dan Simmons"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "MacArthur Park Suite", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Donna Summer"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best of Ed Motta", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ed Motta"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Dune", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Elis Regina"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Dune II", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Frank Herbert"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Dune III", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Frank Herbert"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Unplugged", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Frank Herbert"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Respighi:Pines of Rome", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eugene Ormandy"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Strauss: Waltzes", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eugene Ormandy"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "King For A Day Fool For A Lifetime", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Faith No More"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Deixa Entrar", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Falamansa"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Your Honor [Disc 1]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "George R.R. Martin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Your Honor [Disc 2]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "George R.R. Martin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Colour And The Shape", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "George R.R. Martin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Faceless", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Godsmack"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Appetite for Destruction", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Reiner Knizia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Use Your Illusion I", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Reiner Knizia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Use Your Illusion II", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Reiner Knizia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Blue Moods", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Incognito"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Matter of Life and Death", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Brave New World", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Fear Of The Dark", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live At Donington 1992 (Disc 1)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live At Donington 1992 (Disc 2)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Music In Rio [CD2]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Number of The Beast", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The X Factor", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Virtual XI", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Real Dead One", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Real Live One", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live After Death", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "No Prayer For The Dying", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Piece Of Mind", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Powerslave", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Music In Rio [CD1]", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Music In Rio [CD2]", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Seventh Son of a Seventh Son", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Somewhere in Time", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Number of The Beast", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Iron Maiden", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mascagni: Cavalleria Rusticana", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "James Levine"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Emergency On Planet Earth", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jamiroquai"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Are You Experienced?", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jimi Hendrix"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Jorge Ben Jor 25 Anos", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jorge Ben"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Jota Quest-1995", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jota Quest"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Living After Midnight", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Judas Priest"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "BBC Sessions [Disc 1] [Live]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "BBC Sessions [Disc 2] [Live]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Coda", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Houses Of The Holy", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Through The Out Door", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "IV", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Led Zeppelin I", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Led Zeppelin II", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Led Zeppelin III", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Physical Graffiti [Disc 1]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Physical Graffiti [Disc 2]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Presence", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Song Remains The Same (Disc 1)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Song Remains The Same (Disc 2)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Misplaced Childhood", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marillion"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Barulhinho Bom", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marisa Monte"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best Of Men At Work", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Men At Work"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Miles Ahead", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Essential Miles Davis [Disc 1]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Essential Miles Davis [Disc 2]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Caylus", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "William Attia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mozart: Chamber Music", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nash Ensemble"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Avatar", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "James Cameron"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Nevermind", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nirvana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Olodum", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Olodum"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bach: The Brandenburg Concertos", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Acústico MTV", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Arquivo II", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Arquivo Os Paralamas Do Sucesso", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Tribute", Category = categories.Single(g => g.Name == "Board Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bark at the Moon (Remastered)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Blizzard of Ozz", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Diary of a Madman (Remastered)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "No More Tears (Remastered)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Speak of the Devil", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Walking Into Clarksdale", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Page & Plant"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live On Two Legs [Live]", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Riot Act", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ten", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Vs.", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Dark Side Of The Moon", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pink Floyd"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits I", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits II", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "News Of The World", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "By The Way", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Red Hot Chili Peppers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Californication", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Red Hot Chili Peppers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Santana - As Years Go By", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Santana Live", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Supernatural", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Handel: The Messiah (Highlights)", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Scholars Baroque Ensemble"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Prokofiev: Symphony No.1", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A-Sides", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Soundgarden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Temple of the Dog", Category = categories.Single(g => g.Name == "Computer Games"), Price = 8.99M, Author = authors.Single(a => a.Name == "Temple of the Dog"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Lord of the Ring", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Peter Jackson"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live [Disc 1]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Black Crowes"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live [Disc 2]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Black Crowes"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Beyond Good And Evil", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Cult"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "English Renaissance", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "The King's Singers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Police Greatest Hits", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Police"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Hot Musics, 1964-1971 (Disc 1)", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "No Security", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Voodoo Lounge", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "My Generation - The Very Best Of The Who", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Who"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Serie Sem Limite (Disc 1)", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Tim Maia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Serie Sem Limite (Disc 2)", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Tim Maia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Achtung Baby", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "B-Sides 1980-1990", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "How To Dismantle An Atomic Bomb", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Movies", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Rattle And Hum", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best Of 1980-1990", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "War", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Zooropa", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "UB40 The Best Of - Volume Two [UK]", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "UB40"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Axé Bahia 2001", Category = categories.Single(g => g.Name == "Movies"), Price = 8.99M, Author = authors.Single(a => a.Name == "Terry Pratchett"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Sambas De Enredo 2001", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Terry Pratchett"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Vozes do MPB", Category = categories.Single(g => g.Name == "Books"), Price = 8.99M, Author = authors.Single(a => a.Name == "Terry Pratchett"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Contraband", Category = categories.Single(g => g.Name == "Music"), Price = 8.99M, Author = authors.Single(a => a.Name == "Velvet Revolver"), ItemArtUrl = "/Content/Images/placeholder.gif" },
            
            }.ForEach(a => context.Items.Add(a));
        }
    }
}