using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace WebStore.Models.DataBase
{
    public class SampleData : DropCreateDatabaseIfModelChanges<StoreItemsEntities>
    {
        protected override void Seed(StoreItemsEntities context)
        {
            var categories = new List<Category>
            {
                new Category { Name = "Rock" },
                new Category { Name = "Jazz" },
                new Category { Name = "Metal" },
                new Category { Name = "Alternative" },
                new Category { Name = "Disco" },
                new Category { Name = "Blues" },
                new Category { Name = "Latin" },
                new Category { Name = "Reggae" },
                new Category { Name = "Pop" },
                new Category { Name = "Classical" }
            };

            var authors = new List<Author>
            {
                new Author { Name = "Aaron Copland & London Symphony Orchestra" },
                new Author { Name = "Aaron Goldberg" },
                new Author { Name = "AC/DC" },
                new Author { Name = "Accept" },
                new Author { Name = "Adrian Leaper & Doreen de Feis" },
                new Author { Name = "Aerosmith" },
                new Author { Name = "Aisha Duo" },
                new Author { Name = "Alanis Morissette" },
                new Author { Name = "Alberto Turco & Nova Schola Gregoriana" },
                new Author { Name = "Alice In Chains" },
                new Author { Name = "Amy Winehouse" },
                new Author { Name = "Anita Ward" },
                new Author { Name = "Antônio Carlos Jobim" },
                new Author { Name = "Apocalyptica" },
                new Author { Name = "Audioslave" },
                new Author { Name = "Barry Wordsworth & BBC Concert Orchestra" },
                new Author { Name = "Berliner Philharmoniker & Hans Rosbaud" },
                new Author { Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Author { Name = "Billy Cobham" },
                new Author { Name = "Black Label Society" },
                new Author { Name = "Black Sabbath" },
                new Author { Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Author { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Author { Name = "Bruce Dickinson" },
                new Author { Name = "Buddy Guy" },
                new Author { Name = "Caetano Veloso" },
                new Author { Name = "Cake" },
                new Author { Name = "Calexico" },
                new Author { Name = "Cássia Eller" },
                new Author { Name = "Chic" },
                new Author { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Author { Name = "Chico Buarque" },
                new Author { Name = "Chico Science & Nação Zumbi" },
                new Author { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Author { Name = "Chris Cornell" },
                new Author { Name = "Christopher O'Riley" },
                new Author { Name = "Cidade Negra" },
                new Author { Name = "Cláudio Zoli" },
                new Author { Name = "Creedence Clearwater Revival" },
                new Author { Name = "David Coverdale" },
                new Author { Name = "Deep Purple" },
                new Author { Name = "Dennis Chambers" },
                new Author { Name = "Djavan" },
                new Author { Name = "Donna Summer" },
                new Author { Name = "Dread Zeppelin" },
                new Author { Name = "Ed Motta" },
                new Author { Name = "Edo de Waart & San Francisco Symphony" },
                new Author { Name = "Elis Regina" },
                new Author { Name = "English Concert & Trevor Pinnock" },
                new Author { Name = "Eric Clapton" },
                new Author { Name = "Eugene Ormandy" },
                new Author { Name = "Faith No More" },
                new Author { Name = "Falamansa" },
                new Author { Name = "Foo Fighters" },
                new Author { Name = "Frank Zappa & Captain Beefheart" },
                new Author { Name = "Fretwork" },
                new Author { Name = "Funk Como Le Gusta" },
                new Author { Name = "Gerald Moore" },
                new Author { Name = "Gilberto Gil" },
                new Author { Name = "Godsmack" },
                new Author { Name = "Gonzaguinha" },
                new Author { Name = "Göteborgs Symfoniker & Neeme Järvi" },
                new Author { Name = "Guns N' Roses" },
                new Author { Name = "Gustav Mahler" },
                new Author { Name = "Incognito" },
                new Author { Name = "Iron Maiden" },
                new Author { Name = "James Levine" },
                new Author { Name = "Jamiroquai" },
                new Author { Name = "Jimi Hendrix" },
                new Author { Name = "Joe Satriani" },
                new Author { Name = "Jorge Ben" },
                new Author { Name = "Jota Quest" },
                new Author { Name = "Judas Priest" },
                new Author { Name = "Julian Bream" },
                new Author { Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Author { Name = "Kiss" },
                new Author { Name = "Led Zeppelin" },
                new Author { Name = "Legião Urbana" },
                new Author { Name = "Lenny Kravitz" },
                new Author { Name = "Les Arts Florissants & William Christie" },
                new Author { Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Author { Name = "Luciana Souza/Romero Lubambo" },
                new Author { Name = "Lulu Santos" },
                new Author { Name = "Marcos Valle" },
                new Author { Name = "Marillion" },
                new Author { Name = "Marisa Monte" },
                new Author { Name = "Martin Roscoe" },
                new Author { Name = "Maurizio Pollini" },
                new Author { Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Author { Name = "Men At Work" },
                new Author { Name = "Metallica" },
                new Author { Name = "Michael Tilson Thomas & San Francisco Symphony" },
                new Author { Name = "Miles Davis" },
                new Author { Name = "Milton Nascimento" },
                new Author { Name = "Mötley Crüe" },
                new Author { Name = "Motörhead" },
                new Author { Name = "Nash Ensemble" },
                new Author { Name = "Nicolaus Esterhazy Sinfonia" },
                new Author { Name = "Nirvana" },
                new Author { Name = "O Terço" },
                new Author { Name = "Olodum" },
                new Author { Name = "Orchestra of The Age of Enlightenment" },
                new Author { Name = "Os Paralamas Do Sucesso" },
                new Author { Name = "Ozzy Osbourne" },
                new Author { Name = "Page & Plant" },
                new Author { Name = "Paul D'Ianno" },
                new Author { Name = "Pearl Jam" },
                new Author { Name = "Pink Floyd" },
                new Author { Name = "Queen" },
                new Author { Name = "R.E.M." },
                new Author { Name = "Raul Seixas" },
                new Author { Name = "Red Hot Chili Peppers" },
                new Author { Name = "Roger Norrington, London Classical Players" },
                new Author { Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Author { Name = "Rush" },
                new Author { Name = "Santana" },
                new Author { Name = "Scholars Baroque Ensemble" },
                new Author { Name = "Scorpions" },
                new Author { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Author { Name = "Sir Georg Solti & Wiener Philharmoniker" },
                new Author { Name = "Skank" },
                new Author { Name = "Soundgarden" },
                new Author { Name = "Spyro Gyra" },
                new Author { Name = "Stevie Ray Vaughan & Double Trouble" },
                new Author { Name = "Stone Temple Pilots" },
                new Author { Name = "System Of A Down" },
                new Author { Name = "Temple of the Dog" },
                new Author { Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Author { Name = "The 12 Cellists of The Berlin Philharmonic" },
                new Author { Name = "The Black Crowes" },
                new Author { Name = "The Cult" },
                new Author { Name = "The Doors" },
                new Author { Name = "The King's Singers" },
                new Author { Name = "The Police" },
                new Author { Name = "The Posies" },
                new Author { Name = "The Rolling Stones" },
                new Author { Name = "The Who" },
                new Author { Name = "Tim Maia" },
                new Author { Name = "Ton Koopman" },
                new Author { Name = "U2" },
                new Author { Name = "UB40" },
                new Author { Name = "Van Halen" },
                new Author { Name = "Various Authors" },
                new Author { Name = "Velvet Revolver" },
                new Author { Name = "Vinícius De Moraes" },
                new Author { Name = "Wilhelm Kempff" },
                new Author { Name = "Yehudi Menuhin" },
                new Author { Name = "Yo-Yo Ma" },
                new Author { Name = "Zeca Pagodinho" }
            };

            new List<Item>
            {
                new Item { Title = "A Copland Celebration, Vol. I", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Worlds", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aaron Goldberg"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "For Those About To Rock We Salute You", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "AC/DC"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Let There Be Rock", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "AC/DC"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Balls to the Wall", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Accept"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Restless and Wild", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Accept"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Górecki: Symphony No. 3", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Adrian Leaper & Doreen de Feis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Big Ones", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aerosmith"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Quiet Songs", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Aisha Duo"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Jagged Little Pill", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Alanis Morissette"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Facelift", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Alice In Chains"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Frank", Category = categories.Single(g => g.Name == "Pop"), Price = 8.99M, Author = authors.Single(a => a.Name == "Amy Winehouse"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ring My Bell", Category = categories.Single(g => g.Name == "Disco"), Price = 8.99M, Author = authors.Single(a => a.Name == "Anita Ward"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chill: Brazil (Disc 2)", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Antônio Carlos Jobim"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Warner 25 Anos", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Antônio Carlos Jobim"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Plays Metallica By Four Cellos", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Apocalyptica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Revelations", Category = categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Audioslave"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Audioslave", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Audioslave"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Last Night of the Proms", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Sibelius: Finlandia", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mozart: Symphonies Nos. 40 & 41", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best Of Billy Cobham", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Billy Cobham"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Alcohol Fueled Brewtality Live! [Disc 1]", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Label Society"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Alcohol Fueled Brewtality Live! [Disc 2]", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Label Society"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Black Sabbath Vol. 4 (Remaster)", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Sabbath"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Black Sabbath", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Black Sabbath"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Carmina Burana", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Soprano Inspired", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chemical Wedding", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Bruce Dickinson"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Prenda Minha", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Caetano Veloso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Sozinho Remix Ao Vivo", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Caetano Veloso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Cake: B-Sides and Rarities", Category = categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cake"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Carried to Dust (Bonus Track Version)", Category = categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Calexico"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Cássia Eller - Sem Limite [Disc 1]", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cássia Eller"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Le Freak", Category = categories.Single(g => g.Name == "Disco"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chic"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Scheherazade", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Minha Historia", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Buarque"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Afrociberdelia", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Science & Nação Zumbi"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Da Lama Ao Caos", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chico Science & Nação Zumbi"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Carry On", Category = categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Chris Cornell"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "SCRIABIN: Vers la flamme", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Christopher O'Riley"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Acústico MTV [Live]", Category = categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cidade Negra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Cidade Negra - Hits", Category = categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cidade Negra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Na Pista", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Cláudio Zoli"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chronicle, Vol. 1", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Creedence Clearwater Revival"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chronicle, Vol. 2", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Creedence Clearwater Revival"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Into The Light", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "David Coverdale"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Come Taste The Band", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Deep Purple In Rock", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Fireball", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Machine Head", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "MK III The Final Concerts [Disc 1]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Purpendicular", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Slaves And Masters", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Stormbringer", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Battle Rages On", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Final Concerts (Disc 2)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Deep Purple"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Outbreak", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dennis Chambers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Djavan Ao Vivo - Vol. 02", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Djavan"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Djavan Ao Vivo - Vol. 1", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Djavan"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "MacArthur Park Suite", Category = categories.Single(g => g.Name == "Disco"), Price = 8.99M, Author = authors.Single(a => a.Name == "Donna Summer"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Un-Led-Ed", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Dread Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best of Ed Motta", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ed Motta"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Adams, John: The Chairman Dances", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Edo de Waart & San Francisco Symphony"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Elis Regina-Minha História", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Elis Regina"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Pachelbel: Canon & Gigue", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "English Concert & Trevor Pinnock"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Unplugged", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eric Clapton"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Cream Of Clapton", Category = categories.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eric Clapton"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Unplugged", Category = categories.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eric Clapton"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Respighi:Pines of Rome", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eugene Ormandy"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Strauss: Waltzes", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Eugene Ormandy"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "King For A Day Fool For A Lifetime", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Faith No More"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Deixa Entrar", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Falamansa"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Your Honor [Disc 1]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Foo Fighters"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Your Honor [Disc 2]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Foo Fighters"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Colour And The Shape", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Foo Fighters"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bongo Fury", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Frank Zappa & Captain Beefheart"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Roda De Funk", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Funk Como Le Gusta"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Quanta Gente Veio Ver (Live)", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Gilberto Gil"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Quanta Gente Veio ver--Bônus De Carnaval", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Gilberto Gil"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Faceless", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Godsmack"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Meus Momentos", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Gonzaguinha"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Nielsen: The Six Symphonies", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Appetite for Destruction", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guns N' Roses"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Use Your Illusion I", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guns N' Roses"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Use Your Illusion II", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Guns N' Roses"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Blue Moods", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Incognito"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Matter of Life and Death", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Brave New World", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Fear Of The Dark", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live At Donington 1992 (Disc 1)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live At Donington 1992 (Disc 2)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Rock In Rio [CD2]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Number of The Beast", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The X Factor", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Virtual XI", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Real Dead One", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A Real Live One", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live After Death", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "No Prayer For The Dying", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Piece Of Mind", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Powerslave", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Rock In Rio [CD1]", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Rock In Rio [CD2]", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Seventh Son of a Seventh Son", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Somewhere in Time", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Number of The Beast", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Iron Maiden", Category = categories.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Iron Maiden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mascagni: Cavalleria Rusticana", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "James Levine"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Emergency On Planet Earth", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jamiroquai"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Are You Experienced?", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jimi Hendrix"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Surfing with the Alien (Remastered)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Joe Satriani"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Jorge Ben Jor 25 Anos", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jorge Ben"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Jota Quest-1995", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Jota Quest"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Living After Midnight", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Judas Priest"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Weill: The Seven Deadly Sins", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Kiss", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Kiss"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Unplugged [Live]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Kiss"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "BBC Sessions [Disc 1] [Live]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "BBC Sessions [Disc 2] [Live]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Coda", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Houses Of The Holy", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Through The Out Door", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "IV", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Led Zeppelin I", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Led Zeppelin II", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Led Zeppelin III", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Physical Graffiti [Disc 1]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Physical Graffiti [Disc 2]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Presence", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Song Remains The Same (Disc 1)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Song Remains The Same (Disc 2)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Led Zeppelin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mais Do Mesmo", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Legião Urbana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits", Category = categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Lenny Kravitz"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Tchaikovsky: The Nutcracker", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Duos II", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Luciana Souza/Romero Lubambo"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Chill: Brazil (Disc 1)", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marcos Valle"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Misplaced Childhood", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marillion"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Barulhinho Bom", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Marisa Monte"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Szymanowski: Piano Works, Vol. 1", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Martin Roscoe"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best Of Men At Work", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Men At Work"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "...And Justice For All", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Black Item", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Garage Inc. (Disc 1)", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Garage Inc. (Disc 2)", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Load", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Master Of Puppets", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "ReLoad", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ride The Lightning", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "St. Anger", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Metallica"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Berlioz: Symphonie Fantastique", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Prokofiev: Romeo & Juliet", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Miles Ahead", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Essential Miles Davis [Disc 1]", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Essential Miles Davis [Disc 2]", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Miles Davis"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Milton Nascimento Ao Vivo", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Milton Nascimento"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Minas", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Milton Nascimento"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Motley Crue Greatest Hits", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Mötley Crüe"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ace Of Spades", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Motörhead"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mozart: Chamber Music", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nash Ensemble"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best of Beethoven", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Nevermind", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Nirvana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Compositores", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "O Terço"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Olodum", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Olodum"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bach: The Brandenburg Concertos", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Acústico MTV", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Arquivo II", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Arquivo Os Paralamas Do Sucesso", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Os Paralamas Do Sucesso"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Tribute", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bark at the Moon (Remastered)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Blizzard of Ozz", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Diary of a Madman (Remastered)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "No More Tears (Remastered)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Speak of the Devil", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ozzy Osbourne"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Walking Into Clarksdale", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Page & Plant"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Beast Live", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Paul D'Ianno"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live On Two Legs [Live]", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Riot Act", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ten", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Vs.", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pearl Jam"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Dark Side Of The Moon", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Pink Floyd"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits I", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Greatest Hits II", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "News Of The World", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Queen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "New Adventures In Hi-Fi", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "R.E.M."), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Raul Seixas", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Raul Seixas"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "By The Way", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Red Hot Chili Peppers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Californication", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Red Hot Chili Peppers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Purcell: The Fairy Queen", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Roger Norrington, London Classical Players"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Haydn: Symphonies 99 - 104", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Retrospective I (1974-1980)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Rush"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Santana - As Years Go By", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Santana Live", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Supernatural", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Santana"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Handel: The Messiah (Highlights)", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Scholars Baroque Ensemble"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Prokofiev: Symphony No.1", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Wagner: Favourite Overtures", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Maquinarama", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Skank"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "O Samba Poconé", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Skank"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "A-Sides", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Soundgarden"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Heart of the Night", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Spyro Gyra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Morning Dance", Category = categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Author = authors.Single(a => a.Name == "Spyro Gyra"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "In Step", Category = categories.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Core", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Stone Temple Pilots"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Mezmerize", Category = categories.Single(g => g.Name == "Metal"), Price = 8.99M, Author = authors.Single(a => a.Name == "System Of A Down"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Temple of the Dog", Category = categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Author = authors.Single(a => a.Name == "Temple of the Dog"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "[1997] Black Light Syndrome", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "South American Getaway", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live [Disc 1]", Category = categories.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Black Crowes"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Live [Disc 2]", Category = categories.Single(g => g.Name == "Blues"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Black Crowes"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Beyond Good And Evil", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Cult"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Doors", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Doors"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "English Renaissance", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "The King's Singers"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Police Greatest Hits", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Police"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Every Kind of Light", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Posies"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Hot Rocks, 1964-1971 (Disc 1)", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "No Security", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Voodoo Lounge", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Rolling Stones"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "My Generation - The Very Best Of The Who", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "The Who"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Serie Sem Limite (Disc 1)", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Tim Maia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Serie Sem Limite (Disc 2)", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Tim Maia"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bach: Toccata & Fugue in D Minor", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Ton Koopman"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Achtung Baby", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "B-Sides 1980-1990", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "How To Dismantle An Atomic Bomb", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Pop", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Rattle And Hum", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best Of 1980-1990", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "War", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Zooropa", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "U2"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "UB40 The Best Of - Volume Two [UK]", Category = categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Author = authors.Single(a => a.Name == "UB40"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Diver Down", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "The Best Of Van Halen, Vol. I", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Van Halen III", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Van Halen", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Van Halen"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Axé Bahia 2001", Category = categories.Single(g => g.Name == "Pop"), Price = 8.99M, Author = authors.Single(a => a.Name == "Various Authors"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Sambas De Enredo 2001", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Various Authors"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Vozes do MPB", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Various Authors"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Contraband", Category = categories.Single(g => g.Name == "Rock"), Price = 8.99M, Author = authors.Single(a => a.Name == "Velvet Revolver"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Vinicius De Moraes", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Vinícius De Moraes"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bach: Goldberg Variations", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Wilhelm Kempff"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bartok: Violin & Viola Concertos", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Yehudi Menuhin"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Bach: The Cello Suites", Category = categories.Single(g => g.Name == "Classical"), Price = 8.99M, Author = authors.Single(a => a.Name == "Yo-Yo Ma"), ItemArtUrl = "/Content/Images/placeholder.gif" },
                new Item { Title = "Ao Vivo [IMPORT]", Category = categories.Single(g => g.Name == "Latin"), Price = 8.99M, Author = authors.Single(a => a.Name == "Zeca Pagodinho"), ItemArtUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Items.Add(a));
        }
    }
}